### ISSUE TITLE
Public keyservers are unreliable

### ISSUE THREAD

**Issue by franz-josef-kaiser** [franz-josef-kaiser/Docker-Alpine-Nodejs#11]
The public keyservers keep failing. This is annoying and can stall builds for no local reason. There was the idea…

 * build a quick `--rm` disposable container with a fresh trust db and public keyring
 * import all GPG keys of Nodejs maintainers there
 * map the volume to the host system
 * `ADD` the resulting files to the repo and the image

The following command works:

    docker run -it --rm  -v /tmp/gpg-test:/root/.gnupg ubuntu bash

Big props @guedressel for keeping this repos image safe!

**Comment by franz-josef-kaiser** [comment]
Done with 5316a1d. props @guedressel

**Comment by gdressel** [comment]
cheers!
